Update verify script (#10711)
* Dev-UX: Update verify script to check for docker dependency

We modify the verify script to look for 'docker' so that we can
fail early with a more helpful error message. Future improvements
might try to auto-install docker or at least provide a link to
install in the error output.

Now that the verify script is more than just a couple of commands,
We also change the structure of the 'verify' script to have a 'main'
block.

* Simplify & Fix: Properly skip database tests before database has been started

The verify script has a command to start database, but this is done only after
we have run 'check' in parallel on all sub-modules except for those that
depend on tests. The database dependent tests were specified down to the exact
sub-module, which did not scale as we added a sub-module but did not update
this white list.

The result of having a test start before database is that we got an error message
that the database was not available. This gave the false impression that we
need to start database before running 'verify' (when really it was just broken).

This update resolves this by specifing the lobby top level module that we will
skip without specifying each individual sub-module below the 'lobby top level'.

To better root out any problems with database starting up, we move that to be
started first before we execute any checks.

diff --git a/verify b/verify
--- a/verify
+++ b/verify
@@ -3,19 +3,35 @@
 boldGreen="\e[1m\e[92m"
 normal="\e[0m"
 
-# Note, we cannot run database tests in parallel as they conflict with
-# each other, so we run them in serial after running all other gradle checks
-./gradlew --parallel spotlessApply \
-  -x :spitfire-server:lobby-module:test \
-  -x :spitfire-server:maps-module:test \
-  -x :spitfire-server:dropwizard-server:test \
-  check \
-&& spitfire-server/database/start_docker_db \
-&& ./gradlew \
-  :spitfire-server:lobby-module:test \
-  :spitfire-server:maps-module:test \
-  :spitfire-server:dropwizard-server:test \
-&& .build/code-convention-checks/run \
-&& .build/find-unused-or-unmatched-tests/run \
-&& .build/check-links-and-yaml-syntax/run \
-&& echo -e "${boldGreen}SUCCESS${normal}"
+function main {
+  checkDependency "docker"
+  runBuild
+}
+
+# Verifies a given dependency is installed, if not, aborts
+function checkDependency {
+  local depName="$1"
+  hash "$depName" || quit "ERROR: dependency not installed '$depName'"
+}
+
+function quit {
+  local errorMessage="$1"
+  echo "$errorMessage"
+  exit 1
+}
+
+function runBuild {
+  # Note, we cannot run database tests in parallel as they conflict with
+  # each other, so we run them in serial after running all other gradle checks
+  DATABASE_TESTS=":spitfire-server:check"
+
+  spitfire-server/database/start_docker_db \
+    && ./gradlew --parallel spotlessApply check -x $DATABASE_TESTS \
+    && ./gradlew $DATABASE_TESTS \
+    && .build/code-convention-checks/run \
+    && .build/find-unused-or-unmatched-tests/run \
+    && .build/check-links-and-yaml-syntax/run \
+    && echo -e "${boldGreen}SUCCESS${normal}"
+}
+
+main
