Clean Up and Restructure Travis Build Scripts (#5899)
* Clean Up and Restructure Travis Build Scripts

- **Re-structure Build Scripts**
  - Goal was to make it so .travis.yml contained very little to any logic at all for build commands.
    Second, by grouping build jobs together, the script structure and scope of which scripts were
    used for what is hopefully now more clear.
  - The new script configuration places build scripts into their own folders following this
    convention: '.travis/stages/<stage-name>/<job-name>/run'. Any additional support scripts
    used by a given job will be in the 'job' folder. For most part, any .travis.yml build job
    will just call a 'run' a script and nothing more
  - Scripts that are shared between multiple jobs are now located in '.travis/shared/'

- **Break up Build Jobs**
  - Results in a slightly faster build as we get better parallelism, and the slowest build is now
    slightly faster as it has fewer tasks to perform.
  - Error output is more focused, looking at which build job failed we can get a pretty good idea
    of what went wrong without looking at the logs
  - We get more feedback. Rather than knowing that just tests failed, we can see which parts of the
    build passed and which pieces failed. For example, if there is just a checkstyle violation,
    then we'll see just one failure for checkstyle and everything else would pass.

- **Clean up .travis.yml**
  - Build logic extracted to a 'run' script
  - Lists and maps written with a single line syntax where possible and clean.
  - Common operations, like "install: false", and "cache: .." are extracted to a top level
    where they become common for all jobs.

- **Remove java-11.0.5 install**
  - 11.0.2 is currently doing the job. We added the 11.0.5 install to mitigate a TLS versioning
    issue where connections to JCenter were being rejected due to our version of TLS being too low.
    Background info: https://github.com/triplea-game/triplea/issues/5480
    It appears the problem is currently mitigated or patched on the Travis side as 11.0.2 is working.
    We can restore the 11.0.5 install pretty readily if the need arises again, in the meantime it's
    not necessary (and adds unwanted complexity).

- **Move error reporting to a top-level task (out of build scripts) and be consistent**
  - With all build jobs extracted to folders and invoked on a single line in .travis.yml,
    we can more cleanly execute a build job fail handler by adding "|| $REPORT_FAIL" to
    the end of each run script. This means if any script fails, we'll call the report-fail handler
    to consistently have an issue be created whenever we see a build failure.
    Note: we filter PR builds by checking to see if needed env variables that are only available
    to a master branch build are present, if they are not, the 'report-fail' script is a no-op.

- **Move Succuss Detection to a final Stage**
  - We no longer require a specific script to detect if the build passed and report success. Instead
    there is now a third and final build stage that will report a success and close any 'Build failed'
    issues that may be open. This is in part to make it so that each build script in .travis/ can be
    more focused on just one task.

- **Updates to Prod Deployment - Just Install SSH Keys and Security updates**
  - Implicitly, decided prod deployments will be done 'by-hand'
  - Prod will be updated on every build, but it'll only have SSH keys deployed and security patches
    applied, no binaries or configuration will be changed.

diff --git a/.travis/shared/report-build-status b/.travis/shared/report-build-status
--- a/.travis/shared/report-build-status
+++ b/.travis/shared/report-build-status
@@ -5,6 +5,13 @@
 # On failure, this script will check for an open "build broken" issue and will create one
 # if there is not one already open.
 
+
+if [ -z "$GITHUB_PERSONAL_ACCESS_TOKEN_FOR_TRAVIS" ]; then
+  echo "Aborting issue creation, access token not set. Assuming this is not a 'master' branch build."
+  echo "If the current branch is not 'master', this is fine, otherwise this is a configuration bug."
+  exit 1
+fi
+
 set -eu
 
 # Should be one of {SUCCESS|FAILURE}
