Group run_ansible_prerelease script tasks into functions

diff --git a/infrastructure/run_ansible_prerelease b/infrastructure/run_ansible_prerelease
--- a/infrastructure/run_ansible_prerelease
+++ b/infrastructure/run_ansible_prerelease
@@ -6,12 +6,6 @@
 # If the script is updated, upload a new copy to the infrastructure machine
 # to /home/ansible.
 
-VAULT_PASSWORD_FILE="vault_password"
-if [ ! -f "$VAULT_PASSWORD_FILE" ]; then
-  echo "Error: $VAULT_PASSWORD_FILE must exist"
-  exit 1
-fi
-
 function usage() {
   echo "Usage: $0 [Version] (ansible_args)"
   echo "  version: The version of tripleA we will deploy eg: 1.10.5252"
@@ -28,42 +22,51 @@ fi
 export VERSION=${1-}
 shift
 
-../gradlew :http-server:shadowJar :game-headless:shadowJar :lobby-db:release
-
-ANSIBLE_ROLES_FOLDER="infrastructure/ansible/roles"
-
-mkdir -p "$ANSIBLE_ROLES_FOLDER/database/flyway/files/"
-cp "../lobby-db/build/artifacts/*" "$ANSIBLE_ROLES_FOLDER/database/flyway/files/"
-
-mkdir -p "$ANSIBLE_ROLES_FOLDER/http_server/files/"
-cp "../http-server/build/libs/*" "$ANSIBLE_ROLES_FOLDER/http_server/bot/files/"
-
-mkdir -p "$ANSIBLE_ROLES_FOLDER/bot/files/"
-cp "../game-headless/build/libs/*" "$ANSIBLE_ROLES_FOLDER/bot/files/"
-
-
-HTTP_SERVER_JAR="ansible/roles/http_server/files/triplea-http-server-$VERSION.jar"
-if [ ! -f "$HTTP_SERVER_JAR" ]; then
-  echo "Error: File does not exist: $HTTP_SERVER_JAR"
+VAULT_PASSWORD_FILE="vault_password"
+if [ ! -f "$VAULT_PASSWORD_FILE" ]; then
+  echo "Error: $VAULT_PASSWORD_FILE must exist"
   exit 1
 fi
 
-BOT_JAR="ansible/roles/bot/files/triplea-game-headless-$VERSION.jar"
-if [ ! -f "$BOT_JAR" ]; then
-  echo "Error: File does not exist: $BOT_JAR"
-  exit 1
-fi
 
-MIGRATIONS_ZIP="ansible/roles/flyway/files/migrations.zip"
-if [ ! -f "$MIGRATIONS_ZIP" ]; then
-  echo "Error: File does not exist: $MIGRATIONS_ZIP"
-  exit 1
-fi
+function main() {
+  buildArtifacts
+  addPrivateSshKeyToAgent
+  runDeployment
+}
 
-ansible-vault view --vault-password-file="$VAULT_PASSWORD_FILE" ansible_ssh_key.ed25519 | ssh-add -
+function buildArtifacts() {
+  ../gradlew :http-server:shadowJar :game-headless:shadowJar :lobby-db:release
+  copyBuildArtifact "../lobby-db/build/artifacts/migrations.zip" "ansible/roles/database/flyway/files/"
+  copyBuildArtifact "../http-server/build/artifacts/triplea-http-server-$VERSION.jar" "ansible/roles/http_server/files/"
+  copyBuildArtifact "../game-headless/build/artifacts/triplea-game-headless-$VERSION.jar" "ansible/roles/bot/files/"
+}
 
-ansible-playbook \
-  --vault-password-file "$VAULT_PASSWORD_FILE" \
-  -i ansible/inventory/prerelease \
- "$@" \
- ansible/site.yml
+function copyBuildArtifact() {
+  local -r artifactSource="$1"
+  local -r artifactDestinationPath="$2"
+
+  if [ ! -f "$artifactSource" ]; then
+    echo "Error: File does not exist: $artifactSource"
+    exit 1
+  fi
+
+  mkdir -p "$artifactDestinationPath"
+  cp "$artifactSource" "$artifactDestinationPath"
+}
+
+
+function addPrivateSshKeyToAgent() {
+  ansible-vault view --vault-password-file="$VAULT_PASSWORD_FILE" ansible_ssh_key.ed25519 | ssh-add -
+}
+
+function runDeployment() {
+  ansible-playbook \
+    --vault-password-file "$VAULT_PASSWORD_FILE" \
+    -i ansible/inventory/prerelease \
+   "$@" \
+   ansible/site.yml
+}
+
+main
+
