Update run_deployment script to download http-server artifact and use ansible-vault

diff --git a/infrastructure/run_deployment b/infrastructure/run_deployment
--- a/infrastructure/run_deployment
+++ b/infrastructure/run_deployment
@@ -27,21 +27,36 @@ if [ "$INVENTORY_FILE" != production ] && [ "$INVENTORY_FILE" != prerelease ]; t
   usage
 fi
 
+VAULT_PASSWORD_FILE="vault_password"
+if [ ! -f "$VAULT_PASSWORD_FILE" ]; then
+  echo "Error: $VAULT_PASSWORD_FILE must exist"
+  exit 1
+fi
 
-function downloadAnsible() {
-  # Download ansible files and then extract them
-  DL_LOCATION="https://github.com/triplea-game/triplea/releases/download/$VERSION/ansible.zip"
-  rm -f ansible.zip
-  wget $DL_LOCATION
-  if [ ! -f ansible.zip ]; then
-    echo "ERROR: failed to download ansible.zip from $DL_LOCATION"
-    exit 1
-  fi
-  unzip ansible.zip -d ansible
+if [ ! -f "ansible_ssh_key.ed25519" ]; then
+  echo "Could not find file ansible_ssh_key.ed25519 at current directory"
+  exit 1
+fi
+
+ansible-vault view --vault-password-file="$VAULT_PASSWORD_FILE" ansible_ssh_key.ed25519 | ssh-add -
+
+
+
+function main() {
+
+downloadLobbyJar
+
+downloadHttpServerJar
+
+downloadBotJar
+
+downloadMigrations
+
+ansible-playbook -D -v \
+    --vault-password-file "$VAULT_PASSWORD_FILE" \
+   ansible/site.yml \
+   -i "ansible/inventory/$INVENTORY_FILE"
 }
-
-downloadAnsible
-
 
 function downloadLobbyJar() {
   # Download lobby zip file and copy to ansible roles
@@ -62,8 +77,26 @@ function downloadLobbyJar() {
   mv lobby/bin/triplea-lobby-$VERSION.jar ansible/roles/lobby/files/
 }
 
-downloadLobbyJar
+function downloadHttpServerJar() {
+  HTTP_SERVER_ZIP="triplea-http-server-$VERSION.zip"
+  rm -f $HTTP_SERVER_ZIP
+  HTTP_SERVER_DL_LOCATION="https://github.com/triplea-game/triplea/releases/download/$VERSION/$HTTP_SERVER_ZIP"
+  wget $HTTP_SERVER_DL_LOCATION
+  if [ ! -f "$HTTP_SERVER_ZIP" ]; then
+    echo "ERROR: failed to download http server zip from: $HTTP_SERVER_ZIP"
+    exit 1
+  fi
 
+  rm -rf lobby/
+  unzip $HTTP_SERVER_ZIP -d http-server
+  rm $HTTP_SERVER_ZIP
+
+  mkdir -p ansible/roles/http_server/files/
+  mv http-server/configuration-prerelease.yml \
+     http-server/configuration-production.yml \
+     http-server/bin/triplea-http-server-$VERSION.jar \
+       ansible/roles/http_server/files/
+}
 
 function downloadBotJar() {
   BOT_ZIP="triplea-game-headless-$VERSION.zip"
@@ -80,8 +113,6 @@ function downloadBotJar() {
   mv bot/bin/triplea-game-headless-$VERSION.jar ansible/roles/bot/files/
 }
 
-downloadBotJar
-
 
 function downloadMigrations() {
   local migrationsZip="migrations.zip"
@@ -97,10 +128,4 @@ function downloadMigrations() {
   mv $migrationsZip ansible/roles/flyway/files/
 }
 
-downloadMigrations
-
-source secrets
-ansible-playbook -D -v \
-   ansible/site.yml \
-   -i ansible/inventory/prerelease
-
+main
